import {useEffect,useMemo,useState} from 'react';
import {api} from '../api';
import Modal from '../components/Modal';

const fresh=()=>({name:'',prefix:'',start_counter:1,phone:'',address:'',description:''});

export default function Customers({onNavigate}){
  const [rows,setRows]=useState([]),[open,setOpen]=useState(false),[query,setQuery]=useState(''),[sortBy,setSortBy]=useState('name'),[form,setForm]=useState(fresh),[error,setError]=useState('');
  const load=()=>api.get('/customers/summary').then(setRows).catch(e=>setError(e.message));
  useEffect(()=>{load()},[]);
  const visible=useMemo(()=>{const matched=rows.filter(row=>[row.name,row.prefix,row.phone].join(' ').toLowerCase().includes(query.trim().toLowerCase()));return [...matched].sort((a,b)=>sortBy==='balance'?Number(b.balance||0)-Number(a.balance||0):sortBy==='active'?Number(b.active_order_count||0)-Number(a.active_order_count||0):String(a.name).localeCompare(String(b.name),'fa'))},[rows,query,sortBy]);
  const save=async()=>{setError('');try{await api.post('/customers',{...form,start_counter:Number(form.start_counter)});setOpen(false);setForm(fresh());load()}catch(e){setError(e.message)}};
  const close=()=>{setOpen(false);setError('');setForm(fresh())};
  return <div className="page operational-page customers-page">
    <div className="page-head"><div><div className="eyebrow">پایگاه مشتریان</div><h1>مشتریان</h1><p>شناسه سفارش هر مشتری از یک پیشوند و شمارنده روشن شروع می‌شود.</p></div><button onClick={()=>setOpen(true)}>مشتری جدید</button></div>
    {error&&!open&&<div className="error">{error}</div>}
    <section className="customer-command"><label><span>جست‌وجوی سریع</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="نام، پیشوند یا تلفن مشتری"/></label><label className="customer-sort"><span>ترتیب نمایش</span><select value={sortBy} onChange={e=>setSortBy(e.target.value)}><option value="name">نام مشتری</option><option value="balance">بیشترین مانده وصول</option><option value="active">بیشترین سفارش فعال</option></select></label><b>{visible.length}<small> مشتری در این نما</small></b></section>
    <section className="card operational-table"><div className="section-title"><div><div className="eyebrow">فهرست مشتریان</div><h2>مشتری‌های ثبت‌شده</h2></div><span>برای شروع سفارش، مستقیماً مشتری مدنظر را انتخاب کنید.</span></div><div className="table-wrap"><table><thead><tr><th>نام</th><th>پیشوند</th><th>شماره شروع</th><th>شماره بعدی</th><th>سفارش فعال</th><th>مانده وصول</th><th>تلفن</th><th>نشانی</th><th>اقدام</th></tr></thead><tbody>{visible.map(row=><tr key={row.id}><td><b>{row.name}</b>{row.description&&<small className="block-muted">{row.description}</small>}</td><td><span className="customer-prefix">{row.prefix}</span></td><td>{row.start_counter}</td><td><b>{row.next_order_counter}</b></td><td><b>{row.active_order_count||0}</b><small className="block-muted">از {row.order_count||0} سفارش</small></td><td className={Number(row.balance)>0?'debt-text':''}>{Number(row.balance||0).toLocaleString('fa-IR')}</td><td>{row.phone||'—'}</td><td>{row.address||'—'}</td><td><button className="secondary customer-order-btn" onClick={()=>onNavigate?.('orders',{customerId:row.id})}>سفارش جدید</button></td></tr>)}</tbody></table></div>{visible.length===0&&<div className="empty">مشتری مطابق جست‌وجو پیدا نشد.</div>}</section>
    {open&&<Modal title="مشتری جدید" onClose={close} actions={<><button className="secondary" onClick={close}>انصراف</button><button onClick={save}>ثبت مشتری</button></>}><div className="form-grid compact-form"><label className="field"><span>نام مشتری *</span><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="field"><span>پیشوند سفارش *</span><input value={form.prefix} onChange={e=>setForm({...form,prefix:e.target.value})} placeholder="مثلاً MD"/></label><label className="field important"><span>شماره شروع سفارش *</span><input type="number" min="1" value={form.start_counter} onChange={e=>setForm({...form,start_counter:e.target.value})}/><small>مثلاً برای شروع از MD12 عدد 12 را وارد کنید.</small></label><label className="field"><span>تلفن</span><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label className="field wide"><span>نشانی</span><input value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><label className="field wide"><span>یادداشت یا مشخصه مشتری</span><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="نکتهٔ مهم برای فروش یا تحویل…"/></label></div>{error&&<div className="error">{error}</div>}</Modal>}
  </div>
}
