import {useEffect,useMemo,useState} from 'react';
import {api} from '../api';
import JalaliDateInput from '../components/JalaliDateInput';
import {toJalali,todayISO} from '../jalali';
import Modal from '../components/Modal';
import OrderDrawer from '../components/OrderDrawer';

const initial=()=>({order_id:'',order_item_id:'',shipment_date:todayISO(),quantity:'',destination:'',carrier:'',waybill:'',receiver:'',delivery_status:'ارسال شد',description:'',registered_by:''});

export default function Shipments({onNavigate}){
  const [orders,setOrders]=useState([]),[detail,setDetail]=useState(null),[rows,setRows]=useState([]),[query,setQuery]=useState(''),[dateFrom,setDateFrom]=useState(''),[dateTo,setDateTo]=useState(''),[open,setOpen]=useState(false),[debt,setDebt]=useState(null),[pending,setPending]=useState(null),[archiveOrder,setArchiveOrder]=useState(null),[message,setMessage]=useState(''),[form,setForm]=useState(initial);
  const load=()=>api.get('/shipments').then(setRows).catch(e=>setMessage(e.message));
  useEffect(()=>{api.get('/orders?active_only=true').then(setOrders).catch(e=>setMessage(e.message));load()},[]);
  useEffect(()=>{if(form.order_id)api.get(`/orders/${form.order_id}`).then(setDetail).catch(e=>setMessage(e.message));else setDetail(null)},[form.order_id]);
  const filteredRows=useMemo(()=>rows.filter(row=>{const text=[row.order_no,row.customer_name,row.product_name,row.destination,row.carrier,row.waybill].join(' ').toLowerCase();return (!query||text.includes(query.trim().toLowerCase()))&&(!dateFrom||row.shipment_date>=dateFrom)&&(!dateTo||row.shipment_date<=dateTo)}),[rows,query,dateFrom,dateTo]);
  const selectedItem=detail?.items?.find(item=>String(item.id)===String(form.order_item_id));
  const submit=async payload=>{setMessage('');try{await api.post('/shipments',payload);setForm(initial());setDebt(null);setPending(null);setOpen(false);load();setMessage('ارسال ثبت شد.')}catch(e){if(e.status===409&&e.detail?.code==='DEBT_CONFIRM_REQUIRED'){setDebt(e.detail.debt);setPending(payload);setOpen(false)}else setMessage(e.message)}};
  const save=()=>{const quantity=Number(form.quantity);if(!form.order_id||!form.order_item_id||quantity<=0){setMessage('سفارش، محصول و تعداد ارسال را کامل کنید.');return}if(selectedItem&&quantity>Number(selectedItem.remaining_quantity)){setMessage(`تعداد ارسال از مانده قابل ارسال (${selectedItem.remaining_quantity}) بیشتر است.`);return}submit({...form,order_id:Number(form.order_id),order_item_id:Number(form.order_item_id),quantity,override_debt:false})};
  const close=()=>{setOpen(false);setMessage('');setForm(initial())};
  const openOrder=id=>api.get(`/orders/${id}`).then(setArchiveOrder).catch(e=>setMessage(e.message));
  return <div className="page operational-page">
    <div className="page-head"><div><div className="eyebrow">خروج کالا</div><h1>ارسال</h1><p>محصول را انتخاب کنید، مقدار را ثبت کنید و در صورت بدهی، تصمیم آگاهانه بگیرید.</p></div><button onClick={()=>setOpen(true)}>ثبت ارسال جدید</button></div>
    {message&&!open&&<div className={message.includes('ثبت شد')?'success':'error'}>{message}</div>}
    <section className="card operational-table"><div className="section-title"><div><div className="eyebrow">سابقه خروج</div><h2>آرشیو ارسال</h2></div><span>{filteredRows.length} ارسال در این بازه</span></div><div className="archive-date-filter no-print"><label className="archive-search"><span>جست‌وجو</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="سفارش، مشتری، محصول یا بارنامه"/></label><JalaliDateInput label="ارسال از" value={dateFrom} onChange={setDateFrom}/><JalaliDateInput label="ارسال تا" value={dateTo} onChange={setDateTo}/>{(query||dateFrom||dateTo)&&<button className="secondary" onClick={()=>{setQuery('');setDateFrom('');setDateTo('')}}>پاک کردن</button>}</div><div className="table-wrap"><table><thead><tr><th>سفارش</th><th>مشتری</th><th>محصول</th><th>تعداد</th><th>تاریخ</th><th>بدهی زمان ارسال</th><th>تأیید با بدهی</th></tr></thead><tbody>{filteredRows.map(row=><tr key={row.id}><td><button className="order-no-link" onClick={()=>openOrder(row.order_id)}>{row.order_no}</button></td><td>{row.customer_name}</td><td><b>{row.product_name}</b></td><td>{row.quantity}</td><td>{toJalali(row.shipment_date)}</td><td>{Number(row.debt_at_shipment).toLocaleString('fa-IR')}</td><td>{row.debt_override?'بله':'خیر'}</td></tr>)}</tbody></table></div>{filteredRows.length===0&&<div className="empty">ارسالی در این بازه ثبت نشده است.</div>}</section>
    {open&&<Modal title="ثبت ارسال جدید" onClose={close} actions={<><button className="secondary" onClick={close}>انصراف</button><button onClick={save}>ثبت ارسال</button></>}><div className="form-grid compact-form"><label className="field"><span>سفارش *</span><select value={form.order_id} onChange={e=>setForm({...form,order_id:e.target.value,order_item_id:''})}><option value="">انتخاب سفارش</option>{orders.map(order=><option key={order.id} value={order.id}>{order.customer_name} — {order.order_no}</option>)}</select></label><label className="field"><span>محصول *</span><select disabled={!detail} value={form.order_item_id} onChange={e=>setForm({...form,order_item_id:e.target.value})}><option value="">انتخاب محصول</option>{detail?.items.map(item=><option key={item.id} value={item.id}>{item.product_name} — مانده {item.remaining_quantity}</option>)}</select></label><label className="field"><span>تعداد ارسال *</span><input type="number" min="1" max={selectedItem?.remaining_quantity} value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></label><JalaliDateInput label="تاریخ ارسال" value={form.shipment_date} onChange={value=>setForm({...form,shipment_date:value})}/><label className="field"><span>مقصد</span><input value={form.destination} onChange={e=>setForm({...form,destination:e.target.value})}/></label><label className="field"><span>باربر</span><input value={form.carrier} onChange={e=>setForm({...form,carrier:e.target.value})}/></label><label className="field"><span>بارنامه</span><input value={form.waybill} onChange={e=>setForm({...form,waybill:e.target.value})}/></label><label className="field"><span>تحویل‌گیرنده</span><input value={form.receiver} onChange={e=>setForm({...form,receiver:e.target.value})}/></label><label className="field wide"><span>توضیحات</span><input value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></div>{selectedItem&&<div className="shipment-product-context"><span>کنترل پیش از ثبت ارسال</span><b>{selectedItem.product_name}</b><div><small>مانده قابل ارسال: <strong>{selectedItem.remaining_quantity}</strong></small><small className={Number(detail.balance)>0?'debt-text':''}>مانده وصول سفارش: {Number(detail.balance||0).toLocaleString('fa-IR')}</small></div></div>}{message&&<div className="error">{message}</div>}</Modal>}
    {debt!==null&&<Modal title="هشدار بدهی مشتری" onClose={()=>{setDebt(null);setPending(null)}} actions={<><button className="secondary" onClick={()=>{setDebt(null);setPending(null)}}>لغو ارسال</button><button className="danger-main" onClick={()=>submit({...pending,override_debt:true})}>با وجود بدهی ارسال شود</button></>}><div className="debt-warning"><b>مانده بدهی: {Number(debt).toLocaleString('fa-IR')}</b><p>این ارسال پس از تأیید ثبت می‌شود و هشدار مدیریتی آن تا زمان تسویه باقی می‌ماند.</p></div></Modal>}
    {archiveOrder&&<OrderDrawer order={archiveOrder} onClose={()=>setArchiveOrder(null)} onNavigate={onNavigate} onProduct={(order,item)=>onNavigate?.('reports',{orderId:order.id,productId:item.id})}/>} 
  </div>
}
